### ISSUE TITLE
Items lost after reloading if inv pages > 1

### ISSUE THREAD

**Issue by luojiesi** [limtis0/SkulPatcher#3]
Thanks for the great mod. It worked great for me except for this specific issue. If the inv pages is set to > 1, save & reload would discard all the other items except the first 9 ones. A possible fix could be 1/ set the item limit to be 90 (highest possible value since max inv pages is 10) when game is initiated 2/ reload all items and then 3/ shrink inv pages?

**Comment by limtis0** [comment]
Hello, I am glad you liked the mod :)

The Inventory-size change was not intended to be savable, but since most of the stuff is, I will try to look into the problem.

**Comment by luojiesi** [comment]
Thanks for working on it. Really appreciate it. It only needs to be savable to prevent lost items. If a save doesn't have more than 9 items it could still be 1.

**Comment by limtis0** [comment]
I was banging my head on this for a long time, but eventually managed to get it to work.
You can download the update now :)

By the way, thanks for the star, it means a lot!

I think doing the same for the skulls will be possible as well, but it will be much harder

**Comment by luojiesi** [comment]
Thanks a lot. Trying it out now! Just a quick question, I notice in your commit, you try to call functions from ItemInventoryFuncs. However ItemInventoryFuncs is not defined anywhere in the repo. Is that included in the commit?

**Comment by luojiesi** [comment]
Sorry forgot to update here. Works great! Thanks!

**Comment by limtis0** [comment]
> Thanks a lot. Trying it out now! Just a quick question, I notice in your commit, you try to call functions from ItemInventoryFuncs. However ItemInventoryFuncs is not defined anywhere in the repo. Is that included in the commit?

Nice find. It somehow was not added to the commits. You can look at the source code now :)
